media:
  input: src/assets/images
  output: /images

content:
  - name: home
    label: "Homepage"
    type: collection
    path: src/content/home
    view:
      fields: [slug, title, body]   # slug first → sorts by filename
    fields:
      - name: slug
        label: Filename
        type: string
        computed: "{{ filename }}"   # automatically takes filename
        hidden: true                 # hidden in the editor UI
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text

  - name: about
    label: "Studio"
    type: collection
    path: src/content/about
    view:
      fields: [slug, title, body]
    fields:
      - name: slug
        label: Filename
        type: string
        computed: "{{ filename }}"
        hidden: true
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text

  - name: ourkidsclimate
    label: "Our Kids' Climate"
    type: collection
    path: src/content/ourkidsclimate
    view:
      fields: [slug, title, body]
    fields:
      - name: slug
        label: Filename
        type: string
        computed: "{{ filename }}"
        hidden: true
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
