media:
  input: src/assets/images
  output: /images

content:
  - name: home
    label: "Homepage"
    type: collection
    path: src/content/home
    sort:
      field: slug
      order: asc
    fields:
      - name: slug
        type: string
        computed: "{{ filename }}"
        hidden: true

      - name: title
        type: string
      - name: body
        type: rich-text

  - name: about
    label: "Studio"
    type: collection
    path: src/content/about
    sort:
      field: slug
      order: asc
    fields:
      - name: slug
        type: string
        computed: "{{ filename }}"
        hidden: true

      - name: title
        type: string
      - name: body
        type: rich-text

  - name: ourkidsclimate
    label: "Our Kids' Climate"
    type: collection
    path: src/content/ourkidsclimate
    sort:
      field: slug
      order: asc
    fields:
      - name: slug
        type: string
        computed: "{{ filename }}"
        hidden: true

      - name: title
        type: string
      - name: body
        type: rich-text
