media:
  input: src/assets/images
  output: /images

content:
  - name: home
    label: "Homepage"
    type: collection
    path: src/content/home
    view:
      fields: [ name, title, body ] 
      sort: [ name, title, body ]
      default:
          sort: name
          order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
  - name: about
    label: "Studio"
    type: collection
    path: src/content/about
    view:
      fields: [ name, title, body ] 
      sort: [ name, title, body ]
      default:
          sort: name
          order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
  - name: ourkidsclimate
    label: "Our Kids' Climate"
    type: collection
    path: src/content/ourkidsclimate
    view:
      fields: [ name, title, body ] 
      sort: [ name, title, body ]
      default:
          sort: name
          order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
  - name: electrify
    label: "Electrify London"
    type: collection
    path: src/content/electrify
    view:
      fields: [ name, title, body ] 
      sort: [ name, title, body ]
      default:
          sort: name
          order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
