media:
  input: src/assets/images
  output: /images

content:
  - name: home
    label: "Homepage"
    type: collection
    path: src/content/home
    sort: false
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
  - name: about
    label: "Studio"
    type: collection
    path: src/content/about
    sort: false
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
  - name: ourkidsclimate
    label: "Our Kids' Climate"
    type: collection
    path: src/content/ourkidsclimate
    sort: false
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text