media:
  input: public/thoughts/images
  output: /thoughts/images

content:
  - name: home
    label: "Homepage"
    type: collection
    path: src/content/home
    view:
      fields: [name, title, body]
      sort: [name, title, body]
      default:
        sort: name
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
        
  - name: about
    label: "Studio"
    type: collection
    path: src/content/about
    view:
      fields: [name, title, body]
      sort: [name, title, body]
      default:
        sort: name
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
        
  - name: thoughts
    label: "Thoughts"
    type: collection
    path: src/content/thoughts
    view:
      fields: [date, name, title, body]
      sort: [date, name, title, body]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: rich-text
      - name: author
        label: Author
        type: string
      - name: date
        label: Publish Date
        type: date
        default: "now"
      - name: featuredImage
        label: Featured Image
        type: image
      - name: body
        label: Content
        type: rich-text


        
  - name: ourkidsclimate
    label: "Our Kids' Climate"
    type: collection
    path: src/content/ourkidsclimate
    view:
      fields: [name, title, body]
      sort: [name, title, body]
      default:
        sort: name
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
        
  - name: deartomorrow
    label: "DearTomorrow"
    type: collection
    path: src/content/deartomorrow
    view:
      fields: [name, title, body]
      sort: [name, title, body]
      default:
        sort: name
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
        
  - name: purposedisruptors
    label: "Purpose Disruptors"
    type: collection
    path: src/content/purposedisruptors
    view:
      fields: [name, title, body]
      sort: [name, title, body]
      default:
        sort: name
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
  - name: electrify
    label: "Electrify London"
    type: collection
    path: src/content/electrify
    view:
      fields: [name, title, body]
      sort: [name, title, body]
      default:
        sort: name
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
        
  - name: carspreading
    label: "Carspreading"
    type: collection
    path: src/content/carspreading
    view:
      fields: [name, title, body]
      sort: [name, title, body]
      default:
        sort: name
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
        
  - name: agencyfornature
    label: "Agency for Nature"
    type: collection
    path: src/content/agencyfornature
    view:
      fields: [name, title, body]
      sort: [name, title, body]
      default:
        sort: name
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
        
  - name: cargorevolution
    label: "Cargo Revolution"
    type: collection
    path: src/content/cargorevolution
    view:
      fields: [name, title, body]
      sort: [name, title, body]
      default:
        sort: name
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
        
  - name: parentsforfuture
    label: "Parents for Future"
    type: collection
    path: src/content/parentsforfuture
    view:
      fields: [name, title, body]
      sort: [name, title, body]
      default:
        sort: name
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
        
  - name: globalalliance
    label: "Global Alliance for a Green New Deal"
    type: collection
    path: src/content/globalalliance
    view:
      fields: [name, title, body]
      sort: [name, title, body]
      default:
        sort: name
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
